# Generated by Django 3.0.7 on 2020-06-25 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200625_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='profile_id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_id',
        ),
    ]
